### ISSUE TITLE
Only read config from the default branch or master or something

### ISSUE THREAD

**Issue by Cadair** [astrofrog/baldrick#2]
Probably easiest to implement this in get_config rather than faffing with having to setup an explicit repohandler to do it.

**Comment by astrofrog** [comment]
I agree!

**Comment by Cadair** [comment]
this was in #3 right?

**Comment by astrofrog** [comment]
I don't think I fixed this, but maybe you did?

**Comment by Cadair** [comment]
I am pretty sure I have
