### ISSUE TITLE
Add back a way of skipping pull requests checks based on a label

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/baldrick#6]
In Astropy-bot, we have a way to skip all pull requests checks if a 'Work in progress' or 'Experimental' label is set. Each of these has a custom message. It would be nice to add back a way of conditionally skipping the checks if a label is set. Maybe we could have an ordered dictionary of label -> message as a config item?

**Comment by Cadair** [comment]
I would like to see a standard way for plugins to opt into this rather than doing it at the blueprint level. As we can't know what people want to do with custom PR plugins.

**Comment by astrofrog** [comment]
This is now possible using ``skip_labels``
